name: swiping_project
description: "child free swiping app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  ionicons: ^0.2.2
  auto_direction: ^0.0.7
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  google_sign_in: ^6.2.1
  firebase_core: ^3.5.0
  firebase_auth: ^5.7.0
  get_it: ^7.7.0
  http: ^1.2.3
  provider: ^6.1.3
  cached_network_image: ^3.3.1
  mime: ^1.0.5
  image: ^4.0.20
  file_selector: ^0.9.0
  http_parser: ^4.0.2
  crop_your_image: ^0.7.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  launcher_name: ^1.0.2
  flutter_launcher_icons: ^0.13.1


flutter:

  uses-material-design: true
  assets:
    - assets/icon.png

launcher_name:
  default: "TEST Childfree Swiping"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  web:
    generate: true
    image_path: "assets/icon.png"


